---
galaxy_info:
  author: your name
  description: Installs, Configures and Manages Harbor (docker)
  company:
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.4
  galaxy_tags: []

dependencies: []